### ISSUE TITLE
Technos icons are not explicit

### ISSUE THREAD

**Issue by vinyll** [productownerinTO/producTOwner#4]
The bottom left icons representing the technologies are not clear.
I recognize HTML5 and CSS3 for example, but there's no help when I roll over them nor there's a link telling me more when clicking. However they react (for no reason then?) when rolling over.

**Comment by fuentesloic** [comment]
Yes I know. when I had built this footer, I had a goal in my head (only) and now ... I'm not sure if it's useful or not ... I think If I have a problem with that I could just erase it but it's interesting to show which techno you're able to use and in a same time it's pretty useless because I'm targeting PO job ... What it's your mind about that ?

**Comment by fuentesloic** [comment]
Ok so I finished to think (after 15 minutes ...)
I remove my footer with techno icons,  it's useless because in each project the used technologie would be write.
